config/routes.rb
Rails.application.routes.draw do

  root :to => 'jobs#index'
  
  resources :jobs
  resources :companies
  resources :users, only: [:new, :show, :index, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", :as => :login
  get "/logout" => 'sessions#destroy', :as => :logout

end

app/models/company.rb
class Company < ActiveRecord::Base

  validates :name, presence: true
  validates :image, presence: true
  validates :location, presence: true
  validates :website, presence: true

  has_many :jobs, dependent: :destroy
  belongs_to :user

end

app/models/job.rb
class Job < ActiveRecord::Base

  validates :title, presence: true
  validates :company, presence: true
  validates :title, presence: true
 
  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, 
    if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, 
    if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, 
    if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end

  def user_access? 
    if current_user != @company.user
      redirect_to company_path
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
    user_access?
  end

  def create
    @company = Company.new(company_params)
    user_access?

    if @company.save
      redirect_to company_path(@company), notice: "successful"
    else
      flash.now[:alert] = "Not Saved"
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
    user_access?

  end

  def update
    @company = Company.find(params[:id])
    user_access? 
    if @company.update_attributes(company_params)
      redirect_to company_path(@company), notice: "successful"
    else
      render :edit
    end
  end

  def show
    @company = Company.find(params[:id])
  end

  def index
    @companies = Company.all
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    user_access?

    flash[:success] = "Company deleted"

    redirect_to companies_path, notice: "successful"
  end

  private
    def company_params
      params.require(:company).permit(:name, :image, :benefit, :location, :website, :about_us)     
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @job = Job.new

  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path, notice: "successful"
    else
      flash.now[:alert] = "Couldn't create"
      render new_job_path
    end
  end

  def update
    @job = Job.find(params[:id])
    user_access?

    if @job.update_attributes(job_params)
      redirect_to job_path
    end
  end

  def edit
    @job = Job.find(params[:id])
    user_access?

  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    flash[:success] = "Job Post deleted"

    redirect_to jobs_path, notice: "successful"
  end

  def show
    @job = Job.find(params[:id])

  end

  def index
    @jobs = Job.all
  end




  private
  def job_params
    params.require(:job).permit(:title, :company_id, :job_type, :pay, :exerience, :languages, :apply)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to companies_path, notice: "Logged in Successfully"
    else
      flash.now[:alert] = "Login Failed"
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_back_or_to users_path, notice: "Create Login Successful"
    else 
      render :new
    end
  end

  def show

    @user = User.find(params[:id])
    user_access?

  end

  def index
    @users = User.all
    user_access?

  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/edit.html.erb
<h1>Edit <%= @company.name %></h1>

<div>
  <%= render(:partial => "layouts/companies_form", :locals => {:@company => @company}) %> 
</div>
<div>
 <%= link_to "Delete Company", :company, method: :delete %>
</div>

app/views/companies/index.html.erb
<h1 class="text-center">Company List</h1>

<div class="card card-companies text-center">
  <% @companies.each do |c| %>
    <div class="card-border companies-border">
      <img class="card-img-top" src="<%= c.image %>" alt="Card image cap">
    <div class="card-block">
      <h4 class="card-title"><%= c.name %></h4>
      <p class="card-text">Location: <%= c.location%></p>
    </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item companies-list index-companies-list">About Us: <%= c.about_us %></li>
      </ul>
    <div class="card-block">
      <a href="<%= c.website %>" class="card-link"><%= c.name %> Site</a>
       <p><%= link_to "Open Positions", company_path(c) %> (<%= c.jobs.count %>)</p>
    </div>
    </div>
  <% end %>
</div>

app/views/companies/new.html.erb
<h3>Create a new company profile</h3>

<div>
  <%= render(:partial => "layouts/companies_form", :locals => {:@company => @company}) %>
</div>


 

app/views/companies/show.html.erb
<%= render(:partial => "layouts/companies", :locals => {:@company => @company}) %>
<%= render(:partial => "layouts/job_table", :locals => {:@company => @company}) %>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>


<%= render(:partial => "layouts/jobs_form", :locals => {:jobs => @jobs} ) %>

app/views/jobs/index.html.erb
<h1 class="text-center">Current Job List</h1>
<div class="container container-jobs">
  <div class="row">
    <table class="table table-condensed table-hover col-lg-6">
      <thead>
        <tr>
          <th>Title</th>
          <th>Company Name</th>
          <th>Job Type</th>
          <th>Experience</th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |j| %>
        <tr>
          <td><%= j.title %></td>
          <td><%= j.company.name %></td>
          <td><%= j.job_type %></td>
          <td><%= j.experience %></td>
          <td>
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Details</button>
           <!-- Modal -->
           <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Job Posting</h4>
                </div>
                <div class="modal-body">
                  <%= render(:partial => "layouts/joblist", :locals => {:@job => j}) %>
                </div>
                <div class="modal-footer">
                </div>
              </div>
            </div>
          </div>
        </td> 
        <td><%=link_to "", job_path(j), :method =>:delete, class:"glyphicon glyphicon-trash" %></td> 
        <td><%= link_to "", edit_job_path(j), class:"glyphicon glyphicon-pencil" %></td>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/new.html.erb
<h1>Create a new job posting</h1>

<%= render(:partial => "layouts/jobs_form", :locals => {:jobs => @jobs} ) %>

app/views/jobs/show.html.erb
<h1 class="text-center">Job Profile Page</h1>


<%= render(:partial => "layouts/joblist", :locals => {:@job => @job}) %>

app/views/layouts/_companies.html.erb
<div class="row">
  <div class="card text-center">
    <div class="card-border">
      <img class="card-img-top" src="<%= @company.image %>" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title"><%= @company.name %></h4>
        <p class="card-text">Location: <%= @company.location%></p>
        <a href="<%= @company.website %>" class="card-link"><%= @company.name %> Site</a>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item companies-show-list">About Us: <%= @company.about_us %></li>
        <li class="list-group-item companies-show-list">Benefits: <%= @company.benefit %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_companies_form.html.erb
<div>
  <form>
    <%= form_for @company do |c|%>
    <div>
      <div>
        <%= c.label :name %>
        <%= c.text_field :name %>
      </div>
      <div>
        <%= c.label :Company_Image %>
        <%= c.text_field :image %>
      </div>
      <div>
        <%= c.label :benefit %>
        <%= c.text_area :benefit, size: "60x12" %>
      </div>
      <div>
        <%= c.label :location %>
        <%= c.text_field :location  %>
      </div>
      <div>
        <%= c.label :website_address %>
        <%= c.url_field :website %>
      </div>
      <div>
        <%= c.label :about_us %>
        <%= c.text_area :about_us, size: "60x12" %>
      </div>
      <div>
        <%= c.submit %>
      </div>
    </div>
    <% end %>
  </form>
</div>

app/views/layouts/_job_table.html.erb
<div class="container container-jobs">
  <div class="row">
    <table class="table table-condensed table-hover col-lg-6">
      <thead>
        <tr>
          <th>Title</th>
          <th>Company Name</th>
          <th>Job Type</th>
          <th>Experience</th>
        </tr>
      </thead>

      <tbody>
        <% @company.jobs.each do |j| %>
        <tr>
          <td><%= j.title %></td>
          <td><%= j.company.name %></td>
          <td><%= j.job_type %></td>
          <td><%= j.experience %></td>
          <td></td>
          <td>
           <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
         Details
          </button>
        
          <!-- Modal -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Job Posting</h4>
                </div>
                <div class="modal-body">
                  <%= render(:partial => "layouts/joblist", :locals => {:@job => j}) %>
                </div>
                <div class="modal-footer">

                </div>
              </div>
            </div>
          </div>
        </td> 
        </tr>      
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_joblist.html.erb
<div class="card text-center">
  <img class="card-img-top" data-src="..." alt="Card image cap" <img src="<%= @job.company.image %>" alt="">
  <div class="card-block">
    <h3 class="card-title"><%= @job.title %></h3>
    <p class="card-text"><%= @job.company.name  %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Pay: <%= @job.pay %></li>
    <li class="list-group-item">Languages: <%= @job.languages %></li>
    <li class="list-group-item">Job Type: <%= @job.job_type %></li>
    <li class="list-group-item">Experience: <%= @job.experience %></li>
    <li class="list-group-item">About us: <%= @job.company.about_us %></li>
    <li class="list-group-item">Benefits: <%= @job.company.benefit %></li>
  </ul>
  <div class="card-block">

    <p><%= link_to "Employer's Website", @job.company.website%></p>
    <p><%= link_to "Employer's Profile Page", company_path(@job) %></p>
    <a href="#">Apply Here</a>
  </div>
</div>

app/views/layouts/_jobs_form.html.erb
<%= form_for @job do |j| %>
  <div>
    <%= j.label :Job_title %>
    <%= j.text_field :title %>
  </div>

    <div>
    <%= j.label :Company%>
    <%= select("job", "company_id", Company.all.collect {|c| [ c.name, c.id ] }, {:include_blank => true}) %>
  </div>

  <div>
    <%= j.label :Job_type %>
    <%= j.text_field :job_type %>
  </div>

  <div>
    <%= j.label :Pay %>
    <%= j.text_field :pay %>
  </div>

  <div>
    <%= j.label :Experience_Level %>
    <%= j.text_field :experience %>
  </div>

  <div>
    <%= j.label :Languages_Required %>
    <%= j.text_field :languages %>
  </div>

  <div>
    <%= j.label :How_to_apply %>
    <%= j.text_field :apply %>
  </div>
<%= j.submit %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Job Board</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="active"><%= link_to("Companies", companies_path) %></li>
        <li><%= link_to("Job", jobs_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <p class="navbar-text">Logged in as <%= current_user.email %></p>
        <li><%= link_to "Logout", logout_path, class: "btn btn-default" %></li>
      <% else %>
        <li><%= link_to "Login", "javascript:void(0)", class: "btn btn-default", onclick: "showLogin()" %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobPosting</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script> 

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>   

</head>
<body>
  <%= render(:partial => "layouts/nav_bar") %>
  <nav>
  </nav>
  <section>
  <%= yield %>
  </section>
</body>

</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |u| %>

  <% if u.object.errors.any? %>
    <% u.object.errors.full_messages.each do |e| %>
      <%= e %>
    <% end %>
   <% end %>

  <div>
    <%= u.label :email %>
    <%= u.text_field :email %>
  </div>
  <div>
    <%= u.label :password %>
    <%= u.password_field :password %>
  </div>
  <div>
    <%= u.label :password_confirmation %>
    <%= u.password_field :password_confirmation %>
  </div>
  <div>
    <%= u.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>